'use strict';
/*eslint max-len: ["error", { "code": 350 }]*/
module.exports = {
  Role: [],
  AccessToken: [],
  ACL: [],
  RoleMapping: [],
  coin: [],
  advisory: [],
  // 'disputa': [],
  // instruccion: [],
  offer: [],
  comment: [],
  answer: [],
  market: [],
  project: [],
  title: [],
  idea: [],
  chatroom: [],
  chat: [],
  news: [],
  follow: [],
  signal: [],
  point: [],
  transaction: [],
  request: [],
  complaint: [],
  UserIdentity: [],
  UserCredential: [],
  notification: [],
  exchange: [],
  user: [],
  position: [],
  transaction: [],
  request: [],
  complaint: [],
  UserIdentity: [],
  UserCredential: [],
  notification: [],
  exchange: [],
  user: [],
};

